### ISSUE TITLE
Support for a POSIX OS

### ISSUE THREAD

**Issue by ysangkok** [asmblah/jemul8#5]
This is just a wish, I suppose it's not supported since there is no mention.

What would be needed?

[jsLinux tech notes](http://bellard.org/jslinux/tech.html) mention only:
- 32 bit x86 compatible CPU (I see there is an [EAX register in cpu.js](https://github.com/asmblah/jemul8/blob/master/js/core/classes/cpu.js#L118), so I assume 32-bit support is already here. MikeOS is 16-bit as far as I can see.)
- 8259 Programmble Interrupt Controller
- 8254 Programmble Interrupt Timer
- 16450 UART
- Real Time Clock.
- IDE interface and hard disk.

I suppose [ELKS](http://elks.sourceforge.net/introduction.html) would be better as a first target, since it is specifically designed to run on 8086 class systems.

What about MINIX? NetBSD?

**Comment by asmblah** [comment]
Hi ysangkok,

The issues at the moment include there being only partial support for Protected Mode, and no SIB byte decoding yet. There is also an issue with the PIT which needs resolving - I have begun the process of gradually refactoring with unit tests.

Thank you for the ELKS link - I will look into supporting that OS first as you mentioned. :)

I will leave this issue open until POSIX OSs are supported.

Hope this helps,
Dan

**Comment by ysangkok** [comment]
Thanks for the response, I will close this because it is kinda unactionable and you already know what is missing.
